[workspace]
channels = ["conda-forge", "bioconda"]
name = "ag"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.12, <3.13"
autogluon = "1.4.0.*"
polars = ">=1.38.1,<2"
pandas = ">=2.3.3,<3"
intarna = ">=3.4.1,<4"
pybigwig = ">=0.3.23,<0.4"
shap = ">=0.51.0,<0.52"

[pypi-dependencies]
pyranges = ">=0.1.4, <0.2"
